### ISSUE TITLE
Exception when it finds an empty php file

### ISSUE THREAD

**Issue by bskendig** [zendframework/Namespacer#4]
My project had a zero-byte .php file in it for some reason, and as soon as "namespacer map" encountered the file, it threw an exception:

```
======================================================================
   The application has thrown an exception!
======================================================================
 Zend\Code\Exception\RuntimeException
 No tokens were provided
----------------------------------------------------------------------
phar:///Users/brkendig/Downloads/namespacer.phar/vendor/zendframework/zend-code/Zend/Code/Scanner/TokenArrayScanner.php:2
#0 phar:///Users/brkendig/Downloads/namespacer.phar/vendor/zendframework/zend-code/Zend/Code/Scanner/TokenArrayScanner.php(2): Zend\Code\Scanner\TokenArrayScanner->scan()
#1 phar:///Users/brkendig/Downloads/namespacer.phar/src/Namespacer/Model/Mapper.php(2): Zend\Code\Scanner\TokenArrayScanner->getClassNames()
#2 phar:///Users/brkendig/Downloads/namespacer.phar/src/Namespacer/Model/Mapper.php(2): Namespacer\Model\Mapper->getMapDataForFile('/p4-wdpro/Proje...')
#3 phar:///Users/brkendig/Downloads/namespacer.phar/src/Namespacer/Controller/Controller.php(2): Namespacer\Model\Mapper->getMapDataForDirectory('src/library/PEP...')
#4 phar:///Users/brkendig/Downloads/namespacer.phar/vendor/zendframework/zend-mvc/Zend/Mvc/Controller/AbstractActionController.php(2): Namespacer\Controller\Controller->createMapAction()
#5 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#6 phar:///Users/brkendig/Downloads/namespacer.phar/vendor/zendframework/zend-eventmanager/Zend/EventManager/EventManager.php(2): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#7 phar:///Users/brkendig/Downloads/namespacer.phar/vendor/zendframework/zend-eventmanager/Zend/EventManager/EventManager.php(2): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#8 phar:///Users/brkendig/Downloads/namespacer.phar/vendor/zendframework/zend-mvc/Zend/Mvc/Controller/AbstractController.php(2): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#9 phar:///Users/brkendig/Downloads/namespacer.phar/vendor/zendframework/zend-mvc/Zend/Mvc/DispatchListener.php(2): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Console\Request), Object(Zend\Console\Response))
#10 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#11 phar:///Users/brkendig/Downloads/namespacer.phar/vendor/zendframework/zend-eventmanager/Zend/EventManager/EventManager.php(2): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#12 phar:///Users/brkendig/Downloads/namespacer.phar/vendor/zendframework/zend-eventmanager/Zend/EventManager/EventManager.php(2): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#13 phar:///Users/brkendig/Downloads/namespacer.phar/vendor/zendframework/zend-mvc/Zend/Mvc/Application.php(2): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#14 phar:///Users/brkendig/Downloads/namespacer.phar/namespacer.php(2): Zend\Mvc\Application->run()
#15 /Users/brkendig/Downloads/namespacer.phar(7): require('phar:///Users/b...')
#16 {main}
======================================================================
   Previous Exception(s):
======================================================================
```

I worked around it by deleting the zero-byte file, but first it took quite a bit of divide-and-conquer to figure out what the problem was.

**Comment by giovanniorigins** [comment]
Thanks to your efforts, I just save a bunch of time, thank you good sir @bskendig !
